//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstafetaConsultaEnvios
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchType", Namespace="http://www.estafeta.com/")]
    public partial class SearchType : object
    {
        
        private EstafetaConsultaEnvios.WaybillRange waybillRangeField;
        
        private EstafetaConsultaEnvios.WaybillList waybillListField;
        
        private string typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EstafetaConsultaEnvios.WaybillRange waybillRange
        {
            get
            {
                return this.waybillRangeField;
            }
            set
            {
                this.waybillRangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EstafetaConsultaEnvios.WaybillList waybillList
        {
            get
            {
                return this.waybillListField;
            }
            set
            {
                this.waybillListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaybillRange", Namespace="http://www.estafeta.com/")]
    public partial class WaybillRange : object
    {
        
        private string initialWaybillField;
        
        private string finalWaybillField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string initialWaybill
        {
            get
            {
                return this.initialWaybillField;
            }
            set
            {
                this.initialWaybillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string finalWaybill
        {
            get
            {
                return this.finalWaybillField;
            }
            set
            {
                this.finalWaybillField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaybillList", Namespace="http://www.estafeta.com/")]
    public partial class WaybillList : object
    {
        
        private string waybillTypeField;
        
        private EstafetaConsultaEnvios.ArrayOfString waybillsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string waybillType
        {
            get
            {
                return this.waybillTypeField;
            }
            set
            {
                this.waybillTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EstafetaConsultaEnvios.ArrayOfString waybills
        {
            get
            {
                return this.waybillsField;
            }
            set
            {
                this.waybillsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.estafeta.com/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchConfiguration", Namespace="http://www.estafeta.com/")]
    public partial class SearchConfiguration : object
    {
        
        private bool includeDimensionsField;
        
        private bool includeWaybillReplaceDataField;
        
        private bool includeReturnDocumentDataField;
        
        private bool includeMultipleServiceDataField;
        
        private bool includeInternationalDataField;
        
        private bool includeSignatureField;
        
        private bool includeCustomerInfoField;
        
        private EstafetaConsultaEnvios.HistoryConfiguration historyConfigurationField;
        
        private EstafetaConsultaEnvios.Filter filterTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool includeDimensions
        {
            get
            {
                return this.includeDimensionsField;
            }
            set
            {
                this.includeDimensionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool includeWaybillReplaceData
        {
            get
            {
                return this.includeWaybillReplaceDataField;
            }
            set
            {
                this.includeWaybillReplaceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool includeReturnDocumentData
        {
            get
            {
                return this.includeReturnDocumentDataField;
            }
            set
            {
                this.includeReturnDocumentDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool includeMultipleServiceData
        {
            get
            {
                return this.includeMultipleServiceDataField;
            }
            set
            {
                this.includeMultipleServiceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool includeInternationalData
        {
            get
            {
                return this.includeInternationalDataField;
            }
            set
            {
                this.includeInternationalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool includeSignature
        {
            get
            {
                return this.includeSignatureField;
            }
            set
            {
                this.includeSignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool includeCustomerInfo
        {
            get
            {
                return this.includeCustomerInfoField;
            }
            set
            {
                this.includeCustomerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public EstafetaConsultaEnvios.HistoryConfiguration historyConfiguration
        {
            get
            {
                return this.historyConfigurationField;
            }
            set
            {
                this.historyConfigurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public EstafetaConsultaEnvios.Filter filterType
        {
            get
            {
                return this.filterTypeField;
            }
            set
            {
                this.filterTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryConfiguration", Namespace="http://www.estafeta.com/")]
    public partial class HistoryConfiguration : object
    {
        
        private bool includeHistoryField;
        
        private string historyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool includeHistory
        {
            get
            {
                return this.includeHistoryField;
            }
            set
            {
                this.includeHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string historyType
        {
            get
            {
                return this.historyTypeField;
            }
            set
            {
                this.historyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filter", Namespace="http://www.estafeta.com/")]
    public partial class Filter : object
    {
        
        private bool filterInformationField;
        
        private string filterTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool filterInformation
        {
            get
            {
                return this.filterInformationField;
            }
            set
            {
                this.filterInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string filterType
        {
            get
            {
                return this.filterTypeField;
            }
            set
            {
                this.filterTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://www.estafeta.com/")]
    public partial class QueryResult : object
    {
        
        private string errorCodeField;
        
        private string errorCodeDescriptionSPAField;
        
        private string errorCodeDescriptionENGField;
        
        private EstafetaConsultaEnvios.TrackingData[] trackingDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorCodeDescriptionSPA
        {
            get
            {
                return this.errorCodeDescriptionSPAField;
            }
            set
            {
                this.errorCodeDescriptionSPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorCodeDescriptionENG
        {
            get
            {
                return this.errorCodeDescriptionENGField;
            }
            set
            {
                this.errorCodeDescriptionENGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EstafetaConsultaEnvios.TrackingData[] trackingData
        {
            get
            {
                return this.trackingDataField;
            }
            set
            {
                this.trackingDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingData", Namespace="http://www.estafeta.com/")]
    public partial class TrackingData : object
    {
        
        private string waybillField;
        
        private string shortWaybillIdField;
        
        private string serviceIdField;
        
        private string serviceDescriptionSPAField;
        
        private string serviceDescriptionENGField;
        
        private string customerNumberField;
        
        private string packageTypeField;
        
        private string additionalInformationField;
        
        private string statusSPAField;
        
        private string statusENGField;
        
        private EstafetaConsultaEnvios.PickupData pickupDataField;
        
        private EstafetaConsultaEnvios.DeliveryData deliveryDataField;
        
        private EstafetaConsultaEnvios.Dimensions dimensionsField;
        
        private EstafetaConsultaEnvios.WaybillReplaceData waybillReplaceDataField;
        
        private EstafetaConsultaEnvios.ReturnDocumentData returnDocumentDataField;
        
        private EstafetaConsultaEnvios.MultipleServiceData multipleServiceDataField;
        
        private EstafetaConsultaEnvios.InternationalData internationalDataField;
        
        private EstafetaConsultaEnvios.CustomerInfo customerInfoField;
        
        private EstafetaConsultaEnvios.History[] historyField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string waybill
        {
            get
            {
                return this.waybillField;
            }
            set
            {
                this.waybillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string shortWaybillId
        {
            get
            {
                return this.shortWaybillIdField;
            }
            set
            {
                this.shortWaybillIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string serviceDescriptionSPA
        {
            get
            {
                return this.serviceDescriptionSPAField;
            }
            set
            {
                this.serviceDescriptionSPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serviceDescriptionENG
        {
            get
            {
                return this.serviceDescriptionENGField;
            }
            set
            {
                this.serviceDescriptionENGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string customerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string packageType
        {
            get
            {
                return this.packageTypeField;
            }
            set
            {
                this.packageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalInformation
        {
            get
            {
                return this.additionalInformationField;
            }
            set
            {
                this.additionalInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string statusSPA
        {
            get
            {
                return this.statusSPAField;
            }
            set
            {
                this.statusSPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string statusENG
        {
            get
            {
                return this.statusENGField;
            }
            set
            {
                this.statusENGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public EstafetaConsultaEnvios.PickupData pickupData
        {
            get
            {
                return this.pickupDataField;
            }
            set
            {
                this.pickupDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public EstafetaConsultaEnvios.DeliveryData deliveryData
        {
            get
            {
                return this.deliveryDataField;
            }
            set
            {
                this.deliveryDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public EstafetaConsultaEnvios.Dimensions dimensions
        {
            get
            {
                return this.dimensionsField;
            }
            set
            {
                this.dimensionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public EstafetaConsultaEnvios.WaybillReplaceData waybillReplaceData
        {
            get
            {
                return this.waybillReplaceDataField;
            }
            set
            {
                this.waybillReplaceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public EstafetaConsultaEnvios.ReturnDocumentData returnDocumentData
        {
            get
            {
                return this.returnDocumentDataField;
            }
            set
            {
                this.returnDocumentDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public EstafetaConsultaEnvios.MultipleServiceData multipleServiceData
        {
            get
            {
                return this.multipleServiceDataField;
            }
            set
            {
                this.multipleServiceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public EstafetaConsultaEnvios.InternationalData internationalData
        {
            get
            {
                return this.internationalDataField;
            }
            set
            {
                this.internationalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public EstafetaConsultaEnvios.CustomerInfo customerInfo
        {
            get
            {
                return this.customerInfoField;
            }
            set
            {
                this.customerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public EstafetaConsultaEnvios.History[] history
        {
            get
            {
                return this.historyField;
            }
            set
            {
                this.historyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PickupData", Namespace="http://www.estafeta.com/")]
    public partial class PickupData : object
    {
        
        private string originAcronymField;
        
        private string originNameField;
        
        private string pickupDateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string originAcronym
        {
            get
            {
                return this.originAcronymField;
            }
            set
            {
                this.originAcronymField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string originName
        {
            get
            {
                return this.originNameField;
            }
            set
            {
                this.originNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pickupDateTime
        {
            get
            {
                return this.pickupDateTimeField;
            }
            set
            {
                this.pickupDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryData", Namespace="http://www.estafeta.com/")]
    public partial class DeliveryData : object
    {
        
        private string destinationAcronymField;
        
        private string destinationNameField;
        
        private string deliveryDateTimeField;
        
        private string zipCodeField;
        
        private string receiverNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string destinationAcronym
        {
            get
            {
                return this.destinationAcronymField;
            }
            set
            {
                this.destinationAcronymField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string destinationName
        {
            get
            {
                return this.destinationNameField;
            }
            set
            {
                this.destinationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string deliveryDateTime
        {
            get
            {
                return this.deliveryDateTimeField;
            }
            set
            {
                this.deliveryDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string receiverName
        {
            get
            {
                return this.receiverNameField;
            }
            set
            {
                this.receiverNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dimensions", Namespace="http://www.estafeta.com/")]
    public partial class Dimensions : object
    {
        
        private string weightField;
        
        private string volumetricWeightField;
        
        private string widthField;
        
        private string lengthField;
        
        private string heightField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string volumetricWeight
        {
            get
            {
                return this.volumetricWeightField;
            }
            set
            {
                this.volumetricWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaybillReplaceData", Namespace="http://www.estafeta.com/")]
    public partial class WaybillReplaceData : object
    {
        
        private string originalWaybillField;
        
        private string replaceWaybillField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string originalWaybill
        {
            get
            {
                return this.originalWaybillField;
            }
            set
            {
                this.originalWaybillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string replaceWaybill
        {
            get
            {
                return this.replaceWaybillField;
            }
            set
            {
                this.replaceWaybillField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnDocumentData", Namespace="http://www.estafeta.com/")]
    public partial class ReturnDocumentData : object
    {
        
        private string initialWaybillField;
        
        private string finalWaybillField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string initialWaybill
        {
            get
            {
                return this.initialWaybillField;
            }
            set
            {
                this.initialWaybillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string finalWaybill
        {
            get
            {
                return this.finalWaybillField;
            }
            set
            {
                this.finalWaybillField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultipleServiceData", Namespace="http://www.estafeta.com/")]
    public partial class MultipleServiceData : object
    {
        
        private string precedingWaybillsField;
        
        private string followingWaybillsField;
        
        private EstafetaConsultaEnvios.ArrayOfString waybillListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string precedingWaybills
        {
            get
            {
                return this.precedingWaybillsField;
            }
            set
            {
                this.precedingWaybillsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string followingWaybills
        {
            get
            {
                return this.followingWaybillsField;
            }
            set
            {
                this.followingWaybillsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EstafetaConsultaEnvios.ArrayOfString waybillList
        {
            get
            {
                return this.waybillListField;
            }
            set
            {
                this.waybillListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternationalData", Namespace="http://www.estafeta.com/")]
    public partial class InternationalData : object
    {
        
        private string internationalWaybillField;
        
        private string originCountryCodeField;
        
        private string originCountrySPAField;
        
        private string originCountryENGField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string internationalWaybill
        {
            get
            {
                return this.internationalWaybillField;
            }
            set
            {
                this.internationalWaybillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string originCountryCode
        {
            get
            {
                return this.originCountryCodeField;
            }
            set
            {
                this.originCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string originCountrySPA
        {
            get
            {
                return this.originCountrySPAField;
            }
            set
            {
                this.originCountrySPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string originCountryENG
        {
            get
            {
                return this.originCountryENGField;
            }
            set
            {
                this.originCountryENGField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://www.estafeta.com/")]
    public partial class CustomerInfo : object
    {
        
        private string referenceField;
        
        private string costsCentreField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string costsCentre
        {
            get
            {
                return this.costsCentreField;
            }
            set
            {
                this.costsCentreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="History", Namespace="http://www.estafeta.com/")]
    public partial class History : object
    {
        
        private string eventDateTimeField;
        
        private string eventIdField;
        
        private string eventDescriptionSPAField;
        
        private string eventDescriptionENGField;
        
        private string eventPlaceAcronymField;
        
        private string eventPlaceNameField;
        
        private string exceptionCodeField;
        
        private string exceptionCodeDescriptionSPAField;
        
        private string exceptionCodeDescriptionENGField;
        
        private string exceptionCodeDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string eventDateTime
        {
            get
            {
                return this.eventDateTimeField;
            }
            set
            {
                this.eventDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string eventId
        {
            get
            {
                return this.eventIdField;
            }
            set
            {
                this.eventIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string eventDescriptionSPA
        {
            get
            {
                return this.eventDescriptionSPAField;
            }
            set
            {
                this.eventDescriptionSPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string eventDescriptionENG
        {
            get
            {
                return this.eventDescriptionENGField;
            }
            set
            {
                this.eventDescriptionENGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string eventPlaceAcronym
        {
            get
            {
                return this.eventPlaceAcronymField;
            }
            set
            {
                this.eventPlaceAcronymField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string eventPlaceName
        {
            get
            {
                return this.eventPlaceNameField;
            }
            set
            {
                this.eventPlaceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string exceptionCode
        {
            get
            {
                return this.exceptionCodeField;
            }
            set
            {
                this.exceptionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string exceptionCodeDescriptionSPA
        {
            get
            {
                return this.exceptionCodeDescriptionSPAField;
            }
            set
            {
                this.exceptionCodeDescriptionSPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string exceptionCodeDescriptionENG
        {
            get
            {
                return this.exceptionCodeDescriptionENGField;
            }
            set
            {
                this.exceptionCodeDescriptionENGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string exceptionCodeDetails
        {
            get
            {
                return this.exceptionCodeDetailsField;
            }
            set
            {
                this.exceptionCodeDetailsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.estafeta.com/", ConfigurationName="EstafetaConsultaEnvios.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.estafeta.com/ExecuteQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<EstafetaConsultaEnvios.ExecuteQueryResponse> ExecuteQueryAsync(EstafetaConsultaEnvios.ExecuteQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteQuery", Namespace="http://www.estafeta.com/", Order=0)]
        public EstafetaConsultaEnvios.ExecuteQueryRequestBody Body;
        
        public ExecuteQueryRequest()
        {
        }
        
        public ExecuteQueryRequest(EstafetaConsultaEnvios.ExecuteQueryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.estafeta.com/")]
    public partial class ExecuteQueryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string suscriberId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EstafetaConsultaEnvios.SearchType searchType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EstafetaConsultaEnvios.SearchConfiguration searchConfiguration;
        
        public ExecuteQueryRequestBody()
        {
        }
        
        public ExecuteQueryRequestBody(string suscriberId, string login, string password, EstafetaConsultaEnvios.SearchType searchType, EstafetaConsultaEnvios.SearchConfiguration searchConfiguration)
        {
            this.suscriberId = suscriberId;
            this.login = login;
            this.password = password;
            this.searchType = searchType;
            this.searchConfiguration = searchConfiguration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteQueryResponse", Namespace="http://www.estafeta.com/", Order=0)]
        public EstafetaConsultaEnvios.ExecuteQueryResponseBody Body;
        
        public ExecuteQueryResponse()
        {
        }
        
        public ExecuteQueryResponse(EstafetaConsultaEnvios.ExecuteQueryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.estafeta.com/")]
    public partial class ExecuteQueryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EstafetaConsultaEnvios.QueryResult ExecuteQueryResult;
        
        public ExecuteQueryResponseBody()
        {
        }
        
        public ExecuteQueryResponseBody(EstafetaConsultaEnvios.QueryResult ExecuteQueryResult)
        {
            this.ExecuteQueryResult = ExecuteQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface ServiceSoapChannel : EstafetaConsultaEnvios.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<EstafetaConsultaEnvios.ServiceSoap>, EstafetaConsultaEnvios.ServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EstafetaConsultaEnvios.ExecuteQueryResponse> EstafetaConsultaEnvios.ServiceSoap.ExecuteQueryAsync(EstafetaConsultaEnvios.ExecuteQueryRequest request)
        {
            return base.Channel.ExecuteQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<EstafetaConsultaEnvios.ExecuteQueryResponse> ExecuteQueryAsync(string suscriberId, string login, string password, EstafetaConsultaEnvios.SearchType searchType, EstafetaConsultaEnvios.SearchConfiguration searchConfiguration)
        {
            EstafetaConsultaEnvios.ExecuteQueryRequest inValue = new EstafetaConsultaEnvios.ExecuteQueryRequest();
            inValue.Body = new EstafetaConsultaEnvios.ExecuteQueryRequestBody();
            inValue.Body.suscriberId = suscriberId;
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.searchType = searchType;
            inValue.Body.searchConfiguration = searchConfiguration;
            return ((EstafetaConsultaEnvios.ServiceSoap)(this)).ExecuteQueryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://tracking.estafeta.com/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://tracking.estafeta.com/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
